language: node_js

services:
  - docker

node_js:
  - stable

branches:
  only:
    - master

install:
  - travis_retry yarn install

script:
  - yarn run test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn run semantic-release
