language: node_js

node_js:
  - stable

branches:
  only:
    - master

install:
  - travis_retry yarn install

script:
  - yarn test
  - yarn build

jobs:
  include:
    - stage: release
      node_js: lts/*
      skip_cleanup: true
      script:
        - yarn semantic-release
